-- Lista 5 - a) O nome de todos os produtos e quantas vezes ele foi vendido, mesmo que não tenha sido vendido ainda

SELECT 
NMPRODUCT,
CASE WHEN COUNT(PRODUCTREQUEST.CDPRODUCT) > 1 THEN COUNT(PRODUCTREQUEST.CDPRODUCT) ELSE 0 END AS QTBUY
FROM PRODUCT
JOIN PRODUCTREQUEST ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY PRODUCTREQUEST.CDPRODUCT, PRODUCT.NMPRODUCT

-- Lista 5) - b) O nome do fornecedor, e o número de produtos que ele fornece, mesmo que não tenha fornecido produto algum

SELECT
NMSUPPLIER,
CASE WHEN COUNT(PRODUCT.CDSUPPLIER) > 1 THEN COUNT(PRODUCT.CDSUPPLIER) ELSE 0 END AS QTSUPPLIER
FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY NMSUPPLIER

-- Lista 5 - c) O nome do fornecedor, o produto e qual o total de produtos dele já vendidos. Uma linha do total por fornecedor e uma linha com o total geral;

SELECT 
SUPPLIER.NMSUPPLIER,
PRODUCT.NMPRODUCT,
sum(PRODUCTREQUEST.CDPRODUCT) AS VLTOTAL
FROM PRODUCTREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY ROLLUP (SUPPLIER.NMSUPPLIER, PRODUCT.NMPRODUCT)

-- Lista 5) - d) O nome do cliente, o produto e o total que o cliente já gastou com esse produto. Uma linha com o total por cliente e uma linha com o total geral;

SELECT 
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
SUM(QTAMOUNT * VLUNITARY) AS VLTOTAL
FROM PRODUCTREQUEST
JOIN REQUEST ON REQUEST.CDREQUEST= PRODUCTREQUEST.CDPRODUCT
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY ROLLUP(CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT)

-- Lista 5) - e) O nome e o telefone de todos os clientes que ainda não compraram produtos

SELECT 
NMCUSTOMER,
IDFONE
FROM CUSTOMER
JOIN REQUEST ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
WHERE REQUEST.CDCUSTOMER LIKE CUSTOMER.CDCUSTOMER

-- Lista 5) - f) O nome e o telefone dos fornecedores que fornecem o produto ‘leite em po” ou o produto “agua mineral”

SELECT
NMSUPPLIER,
IDFONE
FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE PRODUCT.NMPRODUCT LIKE 'leite em po' and PRODUCT.NMPRODUCT LIKE  'agua mineral'

-- Lista 5 - g) O nome e o fornecedor do produto que já foi vendido mais que 3 vezes

SELECT 
NMPRODUCT,
SUPPLIER.NMSUPPLIER
FROM PRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
JOIN PRODUCTREQUEST ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT 
WHERE PRODUCTREQUEST.CDPRODUCT > 3













