-- Lista 5 - a) O nome de todos os produtos e quantas vezes ele foi vendido, mesmo que não tenha sido vendido ainda

SELECT 
NMPRODUCT,
CASE WHEN COUNT(PRODUCTREQUEST.CDPRODUCT) > 1 THEN COUNT(PRODUCTREQUEST.CDPRODUCT) ELSE 0 END AS QTBUY
FROM PRODUCT
JOIN PRODUCTREQUEST ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY PRODUCTREQUEST.CDPRODUCT, PRODUCT.NMPRODUCT

-- Lista 5) - b) O nome do fornecedor, e o número de produtos que ele fornece, mesmo que não tenha fornecido produto algum

SELECT
NMSUPPLIER,
CASE WHEN COUNT(PRODUCT.CDSUPPLIER) > 1 THEN COUNT(PRODUCT.CDSUPPLIER) ELSE 0 END AS QTSUPPLIER
FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY NMSUPPLIER
