-- Lista 6 - 1. a) Excluindo todos os clientes que não compraram nada ainda

DELETE CUSTOMER FROM CUSTOMER 
JOIN REQUEST ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
WHERE CUSTOMER.CDCUSTOMER NOT LIKE REQUEST.CDCUSTOMER

-- Lista 6 - 1. b) Excluindo todos os fornecedores que não forneceram nenhum produto

DELETE SUPPLIER FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE SUPPLIER.CDSUPPLIER NOT LIKE PRODUCT.CDSUPPLIER

-- Lista 6 - 1. c) Atualizando o valor de venda pelo preço original do produto

UPDATE PRODUCTREQUEST
SET VLUNITARY = PRODUCT.VLPRICE
FROM PRODUCTREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
  
-- Lista 6 - 1. d) Acrescentando a tabela do fornecedor o campo dsstatus (10)

ALTER TABLE SUPPLIER ADD COLUMN DSSTATUS VARCHAR(140)

-- Lista 6 - 1. e) Atualizando o status do fornecedor para ‘INATIVO’ nos fornecedores que não forneceram nenhum produto

UPDATE SUPPLIER
SET DSSTATUS = 'INATIVO'
FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE SUPPLIER.CDSUPPLIER NOT LIKE PRODUCT.CDSUPPLIER

-- Lista 6 - 1. f) Faça o script que atualize o campo endereço do cliente para ‘DESCONHECIDO’ onde o endereço for NULO

UPDATE CUSTOMER
SET NMADRESS = 'DESCONHECIDO'
FROM CUSTOMER
WHERE CUSTOMER.NMADRESS IS NULL

-- Lista 6 - 1. g) Faça o script que insira todos os produtos em todos os pedidos. Quantidade 10 e preço original do produto.

INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT CDREQUEST, PRODUCT.CDPRODUCT, 10, VLPRICE FROM PRODUCT
CROSS JOIN PRODUCTREQUEST;

-- Lista 6 - 2. a) Todos os produtos comprados por cliente (nome), com o número de vezes que foi comprado, a quantidade total comprada e o valor total já pago por aquele produto

SELECT 
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
COUNT(PRODUCTREQUEST.CDPRODUCT) AS AMOUNT,
SUM(QTAMOUNT) AS TLAMOUNT,
SUM(PRODUCTREQUEST.VLUNITARY)
FROM PRODUCTREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY PRODUCT.NMPRODUCT, CUSTOMER.NMCUSTOMER


-- Lista 6 - 2. b) O número de pedidos e o total comprado por cliente (nome) no ano de 2003;

SELECT
COUNT(DTREQUEST) QTREQUEST,
CUSTOMER.NMCUSTOMER
FROM REQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY CUSTOMER.NMCUSTOMER, DTREQUEST
HAVING YEAR(REQUEST.DTREQUEST) =  2003

-- Lista 6 - 2. c)  O nome do fornecedor, seu telefone, o nome do produto, seu preço e a quantidade em estoque, o fornecedor deve aparecer mesmo que não tenha nenhum produto

SELECT
NMSUPPLIER,
IDFONE,
PRODUCT.NMPRODUCT,
PRODUCT.VLPRICE,
PRODUCT.QTSTOCK
FROM SUPPLIER
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY PRODUCT.CDPRODUCT, SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE, PRODUCT.VLPRICE, PRODUCT.QTSTOCK,PRODUCT.NMPRODUCT


-- Lista 6 - 2. d) O nome do cliente, a data do pedido e o valor total, o cliente deve aparecer mesmo que não tenha feito nenhum pedido

SELECT 
CUSTOMER.NMCUSTOMER,
DTREQUEST,
VLTOTAL
FROM REQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER





















